"""add players.history_fetched_until

Revision ID: 240edd61b6f7
Revises: feb393e1691f
Create Date: 2026-07-09 22:04:40.600680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240edd61b6f7'
down_revision: Union[str, Sequence[str], None] = 'feb393e1691f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('history_fetched_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'history_fetched_until')
    # ### end Alembic commands ###
