"""create players games puzzles

Revision ID: feb393e1691f
Revises: 
Create Date: 2026-07-09 09:33:40.286876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb393e1691f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lichess_id', sa.String(length=12), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_color', sa.String(length=5), nullable=False),
    sa.Column('player_rating', sa.Integer(), nullable=False),
    sa.Column('opponent_name', sa.String(length=30), nullable=False),
    sa.Column('opponent_rating', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(length=20), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('raw_analysis_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_lichess_id'), 'games', ['lichess_id'], unique=True)
    op.create_index(op.f('ix_games_player_id'), 'games', ['player_id'], unique=False)
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('side_to_move', sa.String(length=5), nullable=False),
    sa.Column('solution_uci', sa.String(length=6), nullable=False),
    sa.Column('solution_san', sa.String(length=10), nullable=False),
    sa.Column('played_uci', sa.String(length=6), nullable=False),
    sa.Column('played_san', sa.String(length=10), nullable=False),
    sa.Column('variation_san', sa.Text(), nullable=False),
    sa.Column('win_drop', sa.Float(), nullable=False),
    sa.Column('eval_before_cp', sa.Integer(), nullable=True),
    sa.Column('eval_after_cp', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply')
    )
    op.create_index(op.f('ix_puzzles_game_id'), 'puzzles', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzzles_game_id'), table_name='puzzles')
    op.drop_table('puzzles')
    op.drop_index(op.f('ix_games_player_id'), table_name='games')
    op.drop_index(op.f('ix_games_lichess_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
